### ISSUE TITLE
Гирлянда

### ISSUE THREAD

**Issue by milkina** [Donator0081/Homework#3]
1. Scanner - Имя метода должно быть с маленькой буквы. Имена следует давать в виде сочетания глаголов и существительных: getValue
2. Scanner sc = new Scanner(System.in); вынести в main и передавать в качестве параметра.
3. Вместо i1, i2, i3 используйте более понятные имена
4. runString - пременная i не используется. Уберите ее.
5. state - гирлянда включена, если значение просто больше 0.

**Comment by Donator0081** [comment]
Где именно runString не используется?

**Comment by Donator0081** [comment]
Исправил

**Comment by milkina** [comment]
3. Имена b, c, d не являются более понятными.
Например d - это гирлянда (это не номер лампочки!) . Можно назвать garland.
c - это количество миганий.  Можно назвать amount.
b - переменная счетчика. Обычно ее называют i.

**Comment by Donator0081** [comment]
Исправил

**Comment by milkina** [comment]
i и garland поменяйте именами
i - счетчик
garland - содержимое гирлянды

**Comment by Donator0081** [comment]
Поменял
