### ISSUE TITLE
MassiveChanges

### ISSUE THREAD

**Issue by milkina** [Donator0081/Homework#8]
1. Вместо  if (b1 == false) лучше  if (!b1)
2. Не развернули

**Comment by Donator0081** [comment]
Что значит не развернули?

**Comment by milkina** [comment]
Вместо  if (!b1) должно быть  if (b1)

**Comment by Donator0081** [comment]
Исправил

**Comment by milkina** [comment]
Done
но еще забыла сказать -   boolean b1 = true; перенесите во внешний цикл.

**Comment by Donator0081** [comment]
Перенес
